deepstreamIO/deepstream.io-client-js

Gruntfile.js

Reasoning: files often concocted (use: [jsDelivr CDN](https://github.com/jsdelivr/jsdelivr#load-multiple-files-with-single-http-request), so you'll lose file ID/name & copyright.
Should work, but untested.

+ banner for minified file

---

src/message/connection.js
test-e2e/specs/loginSpec.js
test-unit/unit/message/connectionSpec.js

This adds support to receive data in login callback, e.g:
```javascript
client.login({ username: 'username', password: 'password' }, function(success, event, error, data) {
console.log(data) // { property: 'value' }
})
```
See: [deepstreamIO/deepstream.io#89](https://github.com/deepstreamIO/deepstream.io/pull/89) & [deepstreamIO/deepstream.io#88](https://github.com/deepstreamIO/deepstream.io/issues/88)
@WolframHempel If you look through the tests you'll see that we've got a really ugly implementation due to backwards-compatibility, and we should clean it up as soon as we get ready for a breaking release.

Support for data in login response

---

src/default-options.js
src/message/connection.js

Resolves #289 
I opted for the parameter name `nodeSocketOptions`.
I am not sure how to adjust tests for this since it simply passes straight through to the websocket constructor.
**Changes**
- Allows configuration to pass options to websocket constructor in node

Resolves #289

---

src/record/list.js
test-unit/unit/record/list-spec.js

If the record isn't in a ready state, calls to `list.removeEntry()` and `list.addEntry()` will not work since the queued methods will always ignore the provided index.

index is undefined when record is not ready

---

README.md
package.json
src/client.d.ts

Hi,
I added Typescript definitions to this repository. This should help Typescript developers a lot by providing type declarations for this repository.
See issue #256 
Big thanks to @RichiWIP whom provided the first version of a Typescript declaration file.
I decided to follow Microsoft's recommended new guidelines that suggest bundling the Typescript Declarations with the module and adding a reference to package.json. Therefore developers won't have to download the typescript definitions from an external repository.
see:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
Alternatively we can create a second repository and submit our typings to Microsoft's @types project directly. However, this process is more involved and no longer seems recommended.
I added …

Added Typescript declarations.

---

src/record/json-path.js

This fixes a future TODO on jsonPath.patch where previously deepEquals was excessivly called.

json-path: Optimized patch

---

.gitignore
src/record/json-path.js
test-unit/unit/record/json-pathSpec.js

This is related to https://github.com/deepstreamIO/deepstream.io-client-js/issues/327

Added support for non-NaNish base 16 numbers in jsonpath

---

src/client.d.ts

Add Presence interface
Add presence field in Client

Add presence to d.ts

---

src/message/connection.js
src/record/record.js
test-unit/unit/message/connectionSpec.js
test-unit/unit/record/record-conflictsSpec.js

When the strategy is remote wins and the content is identical, we expect that
the server version number is taken and no actual merge conflict occurs
Fixes #224

fix: Invalid remote wins merge conflicts

---

src/record/record.js
test-unit/unit/record/record-setSpec.js

This is the client check to prevent an invalid update from being sent and thus saving a round trip.
Related PR: https://github.com/deepstreamIO/deepstream.io/pull/608

Client check to invalid update from being sent.

---

src/client.d.ts

This replaces generic Function callback definitions with arrow functions with the types of parameters specified.
This also adds a new ListenResponse interface used in both Record.listen and Event.listen.

Tighten up typescript callback interfaces

---

src/message/connection.js

Socket errors are returned to the client as the string "[object Event]".

Try to stringify message errors so socket errors keep their data.

---

src/record/list.js
test-unit/unit/record/list-spec.js

- extends `setEntries`, `addEntry` & `removeEntry` methods with callback argument which is passed to `record.set`
- adds new promisifed methods: `setEntriesWithAck`, `addEntryWithAck` & `removeEntryWithAck`
See: https://github.com/deepstreamIO/deepstream.io/issues/830

Feat: List methods with write acknowledgement

---

CHANGELOG.md
src/deepstream-client.ts

The overload signature for `login()` was incorrect, causing the following statement to not work as expected:
```
const client = new DeepstreamClient('localhost:6020')
await client.login({ username: 'foo' })
```
Second line yields
```
'await' has no effect on the type of this expression.ts(80007)
```
Because TypeScript resolves the overload that returns `void`.

fix: DeepstreamClient.login() overload signature is incorrect

---

src/connection/connection.spec.ts
src/connection/socket-factory.ts
src/record/record-core.ts

This prevents the client from hanging when a user tries to write to a record with ack but he only has read access.

Fix connection timeouts if server doesn't send something in time

---

src/connection/socket-factory.ts
src/deepstream.ts
src/util/utils.ts

Hi @yasserf, hope everything is ok.
I gave a second thought to the react-native issue and chose not to use the URL api, neither from the browser nor nodejs, since the use case is rather simple, and coded the url string manipulation directly. This allows to use the client in web, nodejs and react-native without adding more external dependencies. This fixes #515
Also exported the client as object in order to maintain the same api in the bundle. This fixes issue #528 
Let me know what you think and I can push the package and changelog updates.
Also, should the main file in the package.json point to the bundle?
Cheers

[task] do not depend on browser or nodejs URL api [fix] export DeepstreamClient as object property in bundle

---

CHANGELOG.md
package-lock.json
package.json
src/record/record-core.ts
src/record/record.ts

I encountered the following issue: calling record.discard() for a record that has been retrieved multiple times does not actually discard all the record instances nor unsubscribes from them. Example:
```
const { Deepstream } = require('@deepstream/server')
const { DeepstreamClient } = require('@deepstream/client')
const run = async () => {
const server = new Deepstream({})
server.start()
server.on('error', (e) => {
console.error(e)
})
server.on('started', () => {
console.log('Started')
const client = new DeepstreamClient('localhost:6020')
client.login(() => {
client.record.getRecord('user').whenReady((record) => {
// log data changes
record.subscribe((data) => {
console.log('subscribed data', data)
})
// this should be logged
record.set('one', 1)
// this is called after the timeout a few …
```

[fix] discard all references of the record

---

CHANGELOG.md
package-lock.json
package.json
src/record/anonymous-record.ts
src/record/list.ts
src/record/record-core.ts
src/record/record.ts
src/util/emitter.ts

This should fix the problems with unsubscribing from a record and keeping other record's subscriptions active.
I had to put a couple more conditions on the emitter file open for review.
The previous pull request was closed to the history rewrite (a bad choice)

fix: provide context for record subscriptions

---

CHANGELOG.md
package-lock.json
package.json
src/record/single-notifier.ts

Adding a notifier when offline called the callback inmediately, but it wasn't removed from the requests object, adn therefore future calls would not send the message

fix: remove callback

---

CHANGELOG.md
README.md
package-lock.json
package.json
scripts/postinstall.js

When building the react native app for production, the minified client file does not compile correctly for react-native's javascript engine. Therefore the non minified bundle must be used and if a minifier is used for building the react-native app, some configuration options must be set that will be described in the website docs.

change bundle file for react-native

---

scripts/postinstall.js

BUGFIX
When installing `@deepstream/client` in `react-native` project on Windows 10 error occurs in `scripts/postinstall.js`.
Powershell command:
```ps
$env:DEEPSTREAM_ENV = "react-native"
yarn add @deepstream/client
```
Error from output
```
Command: node scripts/postinstall.js
Arguments:
Directory: C:\MY_PROJECT\node_modules\@deepstream\client
Output:
internal/modules/cjs/loader.js:638
throw err;
^
Error: Cannot find module 'C:\MY_PROJECT\node_modules\@deepstream\client\scripts\postinstall.jspackage.json'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
```
As you can see, script tries to include `postinstall.jspackage.json` file. This was …

BUGFIX: postinstall: changed basePath resolution to work on windows

---

CHANGELOG.md
package.json
src/connection/socket-factory.ts

On the client side, the original logic is that its checks if a message wasn't received for a `heartbeatInterval` and decide to send a ping. But if the client only just subscribes to the change of server data and not publish any message, the time interval of server data change is always less than `heartBeatInterval`, the client will not send any Ping, so the server will not receive any data from the client, and the client will be considered disconnected.
Change `lastRecievedMessageTimestamp` to `lastSentMessageTimestamp`, which can ensure that the client sends a message to the server at least once in a `heartbeatInterval `.

fix: send ping message based on lastSentMessage timestamp

---

src/record/record-core.ts

I had a producer which frequently updated a record using the "patch" operation (i.e. setting only one property of the record). I noticed that occasionally my subscribers stopped handling updates.
Through debugging I found that when the subscriber stopped handling updates, the record would go into "MERGING" state and then never leave that state. After further debugging, I think that the cause for this is that the record issues a "read" request but forgets to register a callback. Thus, the read response is not handled and the record never leaves the "MERGING" state.
Properly registering the callback for the read request seems to fix the problem I was experiencing.

Fix: Version conflict when receiving 'PATCH' action causes record to go into 'MERGING' state indefinitely
